server:
  port: 8081
link:
  domain: ${DOMAIN:}
page:
  success: ${SUCCESS_PAGE:}
  fail: ${FAIL_PAGE:}
auth:
  jwt:
    secret: ${JWT_SECRET:}
    access: ${ACCESS_LIFESPAN}
    refresh: ${REFRESH_LIFESPAN}
  github:
    id: ${CLIENT_ID:}
    secret: ${CLIENT_SECRET:}
spring:
  profiles:
    include:
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:}
    url: ${MYSQL_URL:}
    username: ${MYSQL_USERNAME:}
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false
  redis:
    host: localhost
    port: ${REDIS_PORT:}
    password: ${REDIS_PASSWORD:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true